name: Publish to Docker Hub

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Master
        uses: actions/checkout@master

      - name: Build & Publish
        uses: elgohr/Publish-Docker-Github-Action@v5
        env:
          REACT_APP_GA_TRACKING_ID: ${{ secrets.GA_TRACKING_ID }}
        with:
          name: halftheopposite/tosios
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          buildargs: REACT_APP_GA_TRACKING_ID
